import { test, expect } from "@playwright/test"

test("main business flow", async ({ request }) => {
  //
  // LOGIN
  //
  const loginResponse = await request.post(
    "/api/auth/login",
    {
      data: {
        email: "superadmin@mail.com",
        password: "password123",
      },
    }
  )

  const loginText =
  await loginResponse.text()

    console.log(
      loginResponse.status()
    )

    console.log(
      loginText
    )
  

  expect(loginResponse.status()).toBe(200)

  const loginBody = await loginResponse.json()

  const token = loginBody.data.accessToken

  expect(token).toBeTruthy()

  //
  // CREATE CONGREGATION
  //
  const unique =
  Date.now().toString()

const congregationResponse =
  await request.post(
    "/api/congregation",
    {
      headers: {
        Authorization: `Bearer ${token}`,
      },

      data: {
        fullName:
          `Playwright ${unique}`,

        nik:
          `3578${unique}`,

        phone:
          `08${unique.slice(-10)}`,

        address:
          "Playwright Address",

        gender:
          "male",

        isMustahik:
          false,
      },
    }
  )

    console.log(
  await congregationResponse.text()
)

  expect(congregationResponse.status()).toBe(201)

  const congregationBody =
    await congregationResponse.json()

  const congregationId =
    congregationBody.data.id

  //
  // CREATE ATTENDANCE SESSION
  //
  const now = new Date()

  const sessionResponse =
    await request.post(
      "/api/attendance",
      {
        headers: {
          Authorization: `Bearer ${token}`,
        },

        data: {
          title: "Playwright Session",

          type: "event",

          sessionDate:
            now.toISOString(),

          startTime:
            now.toISOString(),

          endTime:
            new Date(
              now.getTime() + 3600000
            ).toISOString(),

          notes:
            "Generated by Playwright",
        },
      }
    )

  expect(sessionResponse.status()).toBe(201)

  const sessionBody =
    await sessionResponse.json()

  const sessionId =
    sessionBody.data.id

  //
  // SUBMIT DONATION
  //
  const donationResponse =
    await request.post(
      "/api/donations",
      {
        multipart: {
          donorName:
            "Playwright Donor",

          phone:
            "08123456789",

          amount:
            "100000",

          categoryId:
            "1",
        },
      }
    )

  expect(donationResponse.status()).toBe(201)

  const donationBody =
    await donationResponse.json()

  const donationId =
    donationBody.data.id

  //
  // VERIFY DONATION
  //
  const verifyResponse =
    await request.put(
      `/api/donations/${donationId}/verify`,
      {
        headers: {
          Authorization:
            `Bearer ${token}`,
        },
      }
    )

  expect(
    verifyResponse.status()
  ).toBe(200)

  //
  // ATTENDANCE CHECK-IN
  //
  const checkInResponse =
    await request.post(
      "/api/attendance/checkin",
      {
        data: {
          sessionId,
          congregationId,
          method: "manual",
        },
      }
    )

  expect(
    checkInResponse.status()
  ).toBe(201)

  const checkInBody =
    await checkInResponse.json()

  expect(
    checkInBody.data.id
  ).toBeTruthy()
})